// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	EventTargets string
	EventTypes   string
	Events       string
	Sources      string
	Tokens       string
	Users        string
}{
	EventTargets: "event_targets",
	EventTypes:   "event_types",
	Events:       "events",
	Sources:      "sources",
	Tokens:       "tokens",
	Users:        "users",
}
