// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// EventType is an object representing the database table.
type EventType struct {
	ID                           string            `boil:"id" json:"id" toml:"id" yaml:"id"`
	Version                      int               `boil:"version" json:"version" toml:"version" yaml:"version"`
	Action                       string            `boil:"action" json:"action" toml:"action" yaml:"action"`
	TargetTypes                  types.StringArray `boil:"target_types" json:"target_types" toml:"target_types" yaml:"target_types"`
	ShouldValidateMetadataSchema bool              `boil:"should_validate_metadata_schema" json:"should_validate_metadata_schema" toml:"should_validate_metadata_schema" yaml:"should_validate_metadata_schema"`
	EventSchema                  null.JSON         `boil:"event_schema" json:"event_schema,omitempty" toml:"event_schema" yaml:"event_schema,omitempty"`
	CreatedAt                    time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt                    time.Time         `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *eventTypeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L eventTypeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EventTypeColumns = struct {
	ID                           string
	Version                      string
	Action                       string
	TargetTypes                  string
	ShouldValidateMetadataSchema string
	EventSchema                  string
	CreatedAt                    string
	UpdatedAt                    string
}{
	ID:                           "id",
	Version:                      "version",
	Action:                       "action",
	TargetTypes:                  "target_types",
	ShouldValidateMetadataSchema: "should_validate_metadata_schema",
	EventSchema:                  "event_schema",
	CreatedAt:                    "created_at",
	UpdatedAt:                    "updated_at",
}

var EventTypeTableColumns = struct {
	ID                           string
	Version                      string
	Action                       string
	TargetTypes                  string
	ShouldValidateMetadataSchema string
	EventSchema                  string
	CreatedAt                    string
	UpdatedAt                    string
}{
	ID:                           "event_types.id",
	Version:                      "event_types.version",
	Action:                       "event_types.action",
	TargetTypes:                  "event_types.target_types",
	ShouldValidateMetadataSchema: "event_types.should_validate_metadata_schema",
	EventSchema:                  "event_types.event_schema",
	CreatedAt:                    "event_types.created_at",
	UpdatedAt:                    "event_types.updated_at",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_StringArray struct{ field string }

func (w whereHelpertypes_StringArray) EQ(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_StringArray) NEQ(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_StringArray) LT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_StringArray) LTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_StringArray) GT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_StringArray) GTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var EventTypeWhere = struct {
	ID                           whereHelperstring
	Version                      whereHelperint
	Action                       whereHelperstring
	TargetTypes                  whereHelpertypes_StringArray
	ShouldValidateMetadataSchema whereHelperbool
	EventSchema                  whereHelpernull_JSON
	CreatedAt                    whereHelpertime_Time
	UpdatedAt                    whereHelpertime_Time
}{
	ID:                           whereHelperstring{field: "\"event_types\".\"id\""},
	Version:                      whereHelperint{field: "\"event_types\".\"version\""},
	Action:                       whereHelperstring{field: "\"event_types\".\"action\""},
	TargetTypes:                  whereHelpertypes_StringArray{field: "\"event_types\".\"target_types\""},
	ShouldValidateMetadataSchema: whereHelperbool{field: "\"event_types\".\"should_validate_metadata_schema\""},
	EventSchema:                  whereHelpernull_JSON{field: "\"event_types\".\"event_schema\""},
	CreatedAt:                    whereHelpertime_Time{field: "\"event_types\".\"created_at\""},
	UpdatedAt:                    whereHelpertime_Time{field: "\"event_types\".\"updated_at\""},
}

// EventTypeRels is where relationship names are stored.
var EventTypeRels = struct {
}{}

// eventTypeR is where relationships are stored.
type eventTypeR struct {
}

// NewStruct creates a new relationship struct
func (*eventTypeR) NewStruct() *eventTypeR {
	return &eventTypeR{}
}

// eventTypeL is where Load methods for each relationship are stored.
type eventTypeL struct{}

var (
	eventTypeAllColumns            = []string{"id", "version", "action", "target_types", "should_validate_metadata_schema", "event_schema", "created_at", "updated_at"}
	eventTypeColumnsWithoutDefault = []string{"id", "action", "target_types"}
	eventTypeColumnsWithDefault    = []string{"version", "should_validate_metadata_schema", "event_schema", "created_at", "updated_at"}
	eventTypePrimaryKeyColumns     = []string{"id"}
	eventTypeGeneratedColumns      = []string{}
)

type (
	// EventTypeSlice is an alias for a slice of pointers to EventType.
	// This should almost always be used instead of []EventType.
	EventTypeSlice []*EventType
	// EventTypeHook is the signature for custom EventType hook methods
	EventTypeHook func(context.Context, boil.ContextExecutor, *EventType) error

	eventTypeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	eventTypeType                 = reflect.TypeOf(&EventType{})
	eventTypeMapping              = queries.MakeStructMapping(eventTypeType)
	eventTypePrimaryKeyMapping, _ = queries.BindMapping(eventTypeType, eventTypeMapping, eventTypePrimaryKeyColumns)
	eventTypeInsertCacheMut       sync.RWMutex
	eventTypeInsertCache          = make(map[string]insertCache)
	eventTypeUpdateCacheMut       sync.RWMutex
	eventTypeUpdateCache          = make(map[string]updateCache)
	eventTypeUpsertCacheMut       sync.RWMutex
	eventTypeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var eventTypeAfterSelectMu sync.Mutex
var eventTypeAfterSelectHooks []EventTypeHook

var eventTypeBeforeInsertMu sync.Mutex
var eventTypeBeforeInsertHooks []EventTypeHook
var eventTypeAfterInsertMu sync.Mutex
var eventTypeAfterInsertHooks []EventTypeHook

var eventTypeBeforeUpdateMu sync.Mutex
var eventTypeBeforeUpdateHooks []EventTypeHook
var eventTypeAfterUpdateMu sync.Mutex
var eventTypeAfterUpdateHooks []EventTypeHook

var eventTypeBeforeDeleteMu sync.Mutex
var eventTypeBeforeDeleteHooks []EventTypeHook
var eventTypeAfterDeleteMu sync.Mutex
var eventTypeAfterDeleteHooks []EventTypeHook

var eventTypeBeforeUpsertMu sync.Mutex
var eventTypeBeforeUpsertHooks []EventTypeHook
var eventTypeAfterUpsertMu sync.Mutex
var eventTypeAfterUpsertHooks []EventTypeHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EventType) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EventType) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EventType) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EventType) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EventType) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EventType) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EventType) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EventType) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EventType) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEventTypeHook registers your hook function for all future operations.
func AddEventTypeHook(hookPoint boil.HookPoint, eventTypeHook EventTypeHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		eventTypeAfterSelectMu.Lock()
		eventTypeAfterSelectHooks = append(eventTypeAfterSelectHooks, eventTypeHook)
		eventTypeAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		eventTypeBeforeInsertMu.Lock()
		eventTypeBeforeInsertHooks = append(eventTypeBeforeInsertHooks, eventTypeHook)
		eventTypeBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		eventTypeAfterInsertMu.Lock()
		eventTypeAfterInsertHooks = append(eventTypeAfterInsertHooks, eventTypeHook)
		eventTypeAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		eventTypeBeforeUpdateMu.Lock()
		eventTypeBeforeUpdateHooks = append(eventTypeBeforeUpdateHooks, eventTypeHook)
		eventTypeBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		eventTypeAfterUpdateMu.Lock()
		eventTypeAfterUpdateHooks = append(eventTypeAfterUpdateHooks, eventTypeHook)
		eventTypeAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		eventTypeBeforeDeleteMu.Lock()
		eventTypeBeforeDeleteHooks = append(eventTypeBeforeDeleteHooks, eventTypeHook)
		eventTypeBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		eventTypeAfterDeleteMu.Lock()
		eventTypeAfterDeleteHooks = append(eventTypeAfterDeleteHooks, eventTypeHook)
		eventTypeAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		eventTypeBeforeUpsertMu.Lock()
		eventTypeBeforeUpsertHooks = append(eventTypeBeforeUpsertHooks, eventTypeHook)
		eventTypeBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		eventTypeAfterUpsertMu.Lock()
		eventTypeAfterUpsertHooks = append(eventTypeAfterUpsertHooks, eventTypeHook)
		eventTypeAfterUpsertMu.Unlock()
	}
}

// One returns a single eventType record from the query.
func (q eventTypeQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EventType, error) {
	o := &EventType{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for event_types")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EventType records from the query.
func (q eventTypeQuery) All(ctx context.Context, exec boil.ContextExecutor) (EventTypeSlice, error) {
	var o []*EventType

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EventType slice")
	}

	if len(eventTypeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EventType records in the query.
func (q eventTypeQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count event_types rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q eventTypeQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if event_types exists")
	}

	return count > 0, nil
}

// EventTypes retrieves all the records using an executor.
func EventTypes(mods ...qm.QueryMod) eventTypeQuery {
	mods = append(mods, qm.From("\"event_types\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"event_types\".*"})
	}

	return eventTypeQuery{q}
}

// FindEventType retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEventType(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*EventType, error) {
	eventTypeObj := &EventType{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"event_types\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, eventTypeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from event_types")
	}

	if err = eventTypeObj.doAfterSelectHooks(ctx, exec); err != nil {
		return eventTypeObj, err
	}

	return eventTypeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EventType) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no event_types provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventTypeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	eventTypeInsertCacheMut.RLock()
	cache, cached := eventTypeInsertCache[key]
	eventTypeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			eventTypeAllColumns,
			eventTypeColumnsWithDefault,
			eventTypeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(eventTypeType, eventTypeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(eventTypeType, eventTypeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"event_types\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"event_types\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into event_types")
	}

	if !cached {
		eventTypeInsertCacheMut.Lock()
		eventTypeInsertCache[key] = cache
		eventTypeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EventType.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EventType) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	eventTypeUpdateCacheMut.RLock()
	cache, cached := eventTypeUpdateCache[key]
	eventTypeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			eventTypeAllColumns,
			eventTypePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update event_types, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"event_types\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, eventTypePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(eventTypeType, eventTypeMapping, append(wl, eventTypePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update event_types row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for event_types")
	}

	if !cached {
		eventTypeUpdateCacheMut.Lock()
		eventTypeUpdateCache[key] = cache
		eventTypeUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q eventTypeQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for event_types")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for event_types")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EventTypeSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"event_types\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, eventTypePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in eventType slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all eventType")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EventType) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no event_types provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventTypeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	eventTypeUpsertCacheMut.RLock()
	cache, cached := eventTypeUpsertCache[key]
	eventTypeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			eventTypeAllColumns,
			eventTypeColumnsWithDefault,
			eventTypeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			eventTypeAllColumns,
			eventTypePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert event_types, could not build update column list")
		}

		ret := strmangle.SetComplement(eventTypeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(eventTypePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert event_types, could not build conflict column list")
			}

			conflict = make([]string, len(eventTypePrimaryKeyColumns))
			copy(conflict, eventTypePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"event_types\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(eventTypeType, eventTypeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(eventTypeType, eventTypeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert event_types")
	}

	if !cached {
		eventTypeUpsertCacheMut.Lock()
		eventTypeUpsertCache[key] = cache
		eventTypeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EventType record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EventType) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EventType provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), eventTypePrimaryKeyMapping)
	sql := "DELETE FROM \"event_types\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from event_types")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for event_types")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q eventTypeQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no eventTypeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from event_types")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for event_types")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EventTypeSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(eventTypeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"event_types\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventTypePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from eventType slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for event_types")
	}

	if len(eventTypeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EventType) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEventType(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EventTypeSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EventTypeSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventTypePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"event_types\".* FROM \"event_types\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventTypePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EventTypeSlice")
	}

	*o = slice

	return nil
}

// EventTypeExists checks if the EventType row exists.
func EventTypeExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"event_types\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if event_types exists")
	}

	return exists, nil
}

// Exists checks if the EventType row exists.
func (o *EventType) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EventTypeExists(ctx, exec, o.ID)
}
