// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// EventTypeVersion is an object representing the database table.
type EventTypeVersion struct {
	EventTypeAction string            `boil:"event_type_action" json:"event_type_action" toml:"event_type_action" yaml:"event_type_action"`
	Version         int               `boil:"version" json:"version" toml:"version" yaml:"version"`
	TargetTypes     types.StringArray `boil:"target_types" json:"target_types" toml:"target_types" yaml:"target_types"`
	EventSchema     null.JSON         `boil:"event_schema" json:"event_schema,omitempty" toml:"event_schema" yaml:"event_schema,omitempty"`
	CreatedAt       time.Time         `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *eventTypeVersionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L eventTypeVersionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EventTypeVersionColumns = struct {
	EventTypeAction string
	Version         string
	TargetTypes     string
	EventSchema     string
	CreatedAt       string
}{
	EventTypeAction: "event_type_action",
	Version:         "version",
	TargetTypes:     "target_types",
	EventSchema:     "event_schema",
	CreatedAt:       "created_at",
}

var EventTypeVersionTableColumns = struct {
	EventTypeAction string
	Version         string
	TargetTypes     string
	EventSchema     string
	CreatedAt       string
}{
	EventTypeAction: "event_type_versions.event_type_action",
	Version:         "event_type_versions.version",
	TargetTypes:     "event_type_versions.target_types",
	EventSchema:     "event_type_versions.event_schema",
	CreatedAt:       "event_type_versions.created_at",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_StringArray struct{ field string }

func (w whereHelpertypes_StringArray) EQ(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_StringArray) NEQ(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_StringArray) LT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_StringArray) LTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_StringArray) GT(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_StringArray) GTE(x types.StringArray) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var EventTypeVersionWhere = struct {
	EventTypeAction whereHelperstring
	Version         whereHelperint
	TargetTypes     whereHelpertypes_StringArray
	EventSchema     whereHelpernull_JSON
	CreatedAt       whereHelpertime_Time
}{
	EventTypeAction: whereHelperstring{field: "\"event_type_versions\".\"event_type_action\""},
	Version:         whereHelperint{field: "\"event_type_versions\".\"version\""},
	TargetTypes:     whereHelpertypes_StringArray{field: "\"event_type_versions\".\"target_types\""},
	EventSchema:     whereHelpernull_JSON{field: "\"event_type_versions\".\"event_schema\""},
	CreatedAt:       whereHelpertime_Time{field: "\"event_type_versions\".\"created_at\""},
}

// EventTypeVersionRels is where relationship names are stored.
var EventTypeVersionRels = struct {
	EventTypeActionEventType string
}{
	EventTypeActionEventType: "EventTypeActionEventType",
}

// eventTypeVersionR is where relationships are stored.
type eventTypeVersionR struct {
	EventTypeActionEventType *EventType `boil:"EventTypeActionEventType" json:"EventTypeActionEventType" toml:"EventTypeActionEventType" yaml:"EventTypeActionEventType"`
}

// NewStruct creates a new relationship struct
func (*eventTypeVersionR) NewStruct() *eventTypeVersionR {
	return &eventTypeVersionR{}
}

func (o *EventTypeVersion) GetEventTypeActionEventType() *EventType {
	if o == nil {
		return nil
	}

	return o.R.GetEventTypeActionEventType()
}

func (r *eventTypeVersionR) GetEventTypeActionEventType() *EventType {
	if r == nil {
		return nil
	}

	return r.EventTypeActionEventType
}

// eventTypeVersionL is where Load methods for each relationship are stored.
type eventTypeVersionL struct{}

var (
	eventTypeVersionAllColumns            = []string{"event_type_action", "version", "target_types", "event_schema", "created_at"}
	eventTypeVersionColumnsWithoutDefault = []string{"event_type_action", "target_types"}
	eventTypeVersionColumnsWithDefault    = []string{"version", "event_schema", "created_at"}
	eventTypeVersionPrimaryKeyColumns     = []string{"event_type_action", "version"}
	eventTypeVersionGeneratedColumns      = []string{}
)

type (
	// EventTypeVersionSlice is an alias for a slice of pointers to EventTypeVersion.
	// This should almost always be used instead of []EventTypeVersion.
	EventTypeVersionSlice []*EventTypeVersion
	// EventTypeVersionHook is the signature for custom EventTypeVersion hook methods
	EventTypeVersionHook func(context.Context, boil.ContextExecutor, *EventTypeVersion) error

	eventTypeVersionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	eventTypeVersionType                 = reflect.TypeOf(&EventTypeVersion{})
	eventTypeVersionMapping              = queries.MakeStructMapping(eventTypeVersionType)
	eventTypeVersionPrimaryKeyMapping, _ = queries.BindMapping(eventTypeVersionType, eventTypeVersionMapping, eventTypeVersionPrimaryKeyColumns)
	eventTypeVersionInsertCacheMut       sync.RWMutex
	eventTypeVersionInsertCache          = make(map[string]insertCache)
	eventTypeVersionUpdateCacheMut       sync.RWMutex
	eventTypeVersionUpdateCache          = make(map[string]updateCache)
	eventTypeVersionUpsertCacheMut       sync.RWMutex
	eventTypeVersionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var eventTypeVersionAfterSelectMu sync.Mutex
var eventTypeVersionAfterSelectHooks []EventTypeVersionHook

var eventTypeVersionBeforeInsertMu sync.Mutex
var eventTypeVersionBeforeInsertHooks []EventTypeVersionHook
var eventTypeVersionAfterInsertMu sync.Mutex
var eventTypeVersionAfterInsertHooks []EventTypeVersionHook

var eventTypeVersionBeforeUpdateMu sync.Mutex
var eventTypeVersionBeforeUpdateHooks []EventTypeVersionHook
var eventTypeVersionAfterUpdateMu sync.Mutex
var eventTypeVersionAfterUpdateHooks []EventTypeVersionHook

var eventTypeVersionBeforeDeleteMu sync.Mutex
var eventTypeVersionBeforeDeleteHooks []EventTypeVersionHook
var eventTypeVersionAfterDeleteMu sync.Mutex
var eventTypeVersionAfterDeleteHooks []EventTypeVersionHook

var eventTypeVersionBeforeUpsertMu sync.Mutex
var eventTypeVersionBeforeUpsertHooks []EventTypeVersionHook
var eventTypeVersionAfterUpsertMu sync.Mutex
var eventTypeVersionAfterUpsertHooks []EventTypeVersionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EventTypeVersion) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeVersionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EventTypeVersion) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeVersionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EventTypeVersion) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeVersionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EventTypeVersion) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeVersionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EventTypeVersion) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeVersionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EventTypeVersion) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeVersionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EventTypeVersion) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeVersionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EventTypeVersion) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeVersionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EventTypeVersion) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range eventTypeVersionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEventTypeVersionHook registers your hook function for all future operations.
func AddEventTypeVersionHook(hookPoint boil.HookPoint, eventTypeVersionHook EventTypeVersionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		eventTypeVersionAfterSelectMu.Lock()
		eventTypeVersionAfterSelectHooks = append(eventTypeVersionAfterSelectHooks, eventTypeVersionHook)
		eventTypeVersionAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		eventTypeVersionBeforeInsertMu.Lock()
		eventTypeVersionBeforeInsertHooks = append(eventTypeVersionBeforeInsertHooks, eventTypeVersionHook)
		eventTypeVersionBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		eventTypeVersionAfterInsertMu.Lock()
		eventTypeVersionAfterInsertHooks = append(eventTypeVersionAfterInsertHooks, eventTypeVersionHook)
		eventTypeVersionAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		eventTypeVersionBeforeUpdateMu.Lock()
		eventTypeVersionBeforeUpdateHooks = append(eventTypeVersionBeforeUpdateHooks, eventTypeVersionHook)
		eventTypeVersionBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		eventTypeVersionAfterUpdateMu.Lock()
		eventTypeVersionAfterUpdateHooks = append(eventTypeVersionAfterUpdateHooks, eventTypeVersionHook)
		eventTypeVersionAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		eventTypeVersionBeforeDeleteMu.Lock()
		eventTypeVersionBeforeDeleteHooks = append(eventTypeVersionBeforeDeleteHooks, eventTypeVersionHook)
		eventTypeVersionBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		eventTypeVersionAfterDeleteMu.Lock()
		eventTypeVersionAfterDeleteHooks = append(eventTypeVersionAfterDeleteHooks, eventTypeVersionHook)
		eventTypeVersionAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		eventTypeVersionBeforeUpsertMu.Lock()
		eventTypeVersionBeforeUpsertHooks = append(eventTypeVersionBeforeUpsertHooks, eventTypeVersionHook)
		eventTypeVersionBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		eventTypeVersionAfterUpsertMu.Lock()
		eventTypeVersionAfterUpsertHooks = append(eventTypeVersionAfterUpsertHooks, eventTypeVersionHook)
		eventTypeVersionAfterUpsertMu.Unlock()
	}
}

// One returns a single eventTypeVersion record from the query.
func (q eventTypeVersionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EventTypeVersion, error) {
	o := &EventTypeVersion{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for event_type_versions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EventTypeVersion records from the query.
func (q eventTypeVersionQuery) All(ctx context.Context, exec boil.ContextExecutor) (EventTypeVersionSlice, error) {
	var o []*EventTypeVersion

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EventTypeVersion slice")
	}

	if len(eventTypeVersionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EventTypeVersion records in the query.
func (q eventTypeVersionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count event_type_versions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q eventTypeVersionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if event_type_versions exists")
	}

	return count > 0, nil
}

// EventTypeActionEventType pointed to by the foreign key.
func (o *EventTypeVersion) EventTypeActionEventType(mods ...qm.QueryMod) eventTypeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"action\" = ?", o.EventTypeAction),
	}

	queryMods = append(queryMods, mods...)

	return EventTypes(queryMods...)
}

// LoadEventTypeActionEventType allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (eventTypeVersionL) LoadEventTypeActionEventType(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEventTypeVersion any, mods queries.Applicator) error {
	var slice []*EventTypeVersion
	var object *EventTypeVersion

	if singular {
		var ok bool
		object, ok = maybeEventTypeVersion.(*EventTypeVersion)
		if !ok {
			object = new(EventTypeVersion)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEventTypeVersion)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEventTypeVersion))
			}
		}
	} else {
		s, ok := maybeEventTypeVersion.(*[]*EventTypeVersion)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEventTypeVersion)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEventTypeVersion))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &eventTypeVersionR{}
		}
		args[object.EventTypeAction] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &eventTypeVersionR{}
			}

			args[obj.EventTypeAction] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`event_types`),
		qm.WhereIn(`event_types.action in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load EventType")
	}

	var resultSlice []*EventType
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice EventType")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for event_types")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for event_types")
	}

	if len(eventTypeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.EventTypeActionEventType = foreign
		if foreign.R == nil {
			foreign.R = &eventTypeR{}
		}
		foreign.R.EventTypeActionEventTypeVersions = append(foreign.R.EventTypeActionEventTypeVersions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.EventTypeAction == foreign.Action {
				local.R.EventTypeActionEventType = foreign
				if foreign.R == nil {
					foreign.R = &eventTypeR{}
				}
				foreign.R.EventTypeActionEventTypeVersions = append(foreign.R.EventTypeActionEventTypeVersions, local)
				break
			}
		}
	}

	return nil
}

// SetEventTypeActionEventType of the eventTypeVersion to the related item.
// Sets o.R.EventTypeActionEventType to related.
// Adds o to related.R.EventTypeActionEventTypeVersions.
func (o *EventTypeVersion) SetEventTypeActionEventType(ctx context.Context, exec boil.ContextExecutor, insert bool, related *EventType) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"event_type_versions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"event_type_action"}),
		strmangle.WhereClause("\"", "\"", 2, eventTypeVersionPrimaryKeyColumns),
	)
	values := []any{related.Action, o.EventTypeAction, o.Version}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.EventTypeAction = related.Action
	if o.R == nil {
		o.R = &eventTypeVersionR{
			EventTypeActionEventType: related,
		}
	} else {
		o.R.EventTypeActionEventType = related
	}

	if related.R == nil {
		related.R = &eventTypeR{
			EventTypeActionEventTypeVersions: EventTypeVersionSlice{o},
		}
	} else {
		related.R.EventTypeActionEventTypeVersions = append(related.R.EventTypeActionEventTypeVersions, o)
	}

	return nil
}

// EventTypeVersions retrieves all the records using an executor.
func EventTypeVersions(mods ...qm.QueryMod) eventTypeVersionQuery {
	mods = append(mods, qm.From("\"event_type_versions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"event_type_versions\".*"})
	}

	return eventTypeVersionQuery{q}
}

// FindEventTypeVersion retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEventTypeVersion(ctx context.Context, exec boil.ContextExecutor, eventTypeAction string, version int, selectCols ...string) (*EventTypeVersion, error) {
	eventTypeVersionObj := &EventTypeVersion{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"event_type_versions\" where \"event_type_action\"=$1 AND \"version\"=$2", sel,
	)

	q := queries.Raw(query, eventTypeAction, version)

	err := q.Bind(ctx, exec, eventTypeVersionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from event_type_versions")
	}

	if err = eventTypeVersionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return eventTypeVersionObj, err
	}

	return eventTypeVersionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EventTypeVersion) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no event_type_versions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventTypeVersionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	eventTypeVersionInsertCacheMut.RLock()
	cache, cached := eventTypeVersionInsertCache[key]
	eventTypeVersionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			eventTypeVersionAllColumns,
			eventTypeVersionColumnsWithDefault,
			eventTypeVersionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(eventTypeVersionType, eventTypeVersionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(eventTypeVersionType, eventTypeVersionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"event_type_versions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"event_type_versions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into event_type_versions")
	}

	if !cached {
		eventTypeVersionInsertCacheMut.Lock()
		eventTypeVersionInsertCache[key] = cache
		eventTypeVersionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EventTypeVersion.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EventTypeVersion) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	eventTypeVersionUpdateCacheMut.RLock()
	cache, cached := eventTypeVersionUpdateCache[key]
	eventTypeVersionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			eventTypeVersionAllColumns,
			eventTypeVersionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update event_type_versions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"event_type_versions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, eventTypeVersionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(eventTypeVersionType, eventTypeVersionMapping, append(wl, eventTypeVersionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update event_type_versions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for event_type_versions")
	}

	if !cached {
		eventTypeVersionUpdateCacheMut.Lock()
		eventTypeVersionUpdateCache[key] = cache
		eventTypeVersionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q eventTypeVersionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for event_type_versions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for event_type_versions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EventTypeVersionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventTypeVersionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"event_type_versions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, eventTypeVersionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in eventTypeVersion slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all eventTypeVersion")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EventTypeVersion) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no event_type_versions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(eventTypeVersionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	eventTypeVersionUpsertCacheMut.RLock()
	cache, cached := eventTypeVersionUpsertCache[key]
	eventTypeVersionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			eventTypeVersionAllColumns,
			eventTypeVersionColumnsWithDefault,
			eventTypeVersionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			eventTypeVersionAllColumns,
			eventTypeVersionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert event_type_versions, could not build update column list")
		}

		ret := strmangle.SetComplement(eventTypeVersionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(eventTypeVersionPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert event_type_versions, could not build conflict column list")
			}

			conflict = make([]string, len(eventTypeVersionPrimaryKeyColumns))
			copy(conflict, eventTypeVersionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"event_type_versions\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(eventTypeVersionType, eventTypeVersionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(eventTypeVersionType, eventTypeVersionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert event_type_versions")
	}

	if !cached {
		eventTypeVersionUpsertCacheMut.Lock()
		eventTypeVersionUpsertCache[key] = cache
		eventTypeVersionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EventTypeVersion record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EventTypeVersion) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EventTypeVersion provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), eventTypeVersionPrimaryKeyMapping)
	sql := "DELETE FROM \"event_type_versions\" WHERE \"event_type_action\"=$1 AND \"version\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from event_type_versions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for event_type_versions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q eventTypeVersionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no eventTypeVersionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from event_type_versions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for event_type_versions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EventTypeVersionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(eventTypeVersionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventTypeVersionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"event_type_versions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventTypeVersionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from eventTypeVersion slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for event_type_versions")
	}

	if len(eventTypeVersionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EventTypeVersion) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEventTypeVersion(ctx, exec, o.EventTypeAction, o.Version)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EventTypeVersionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EventTypeVersionSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), eventTypeVersionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"event_type_versions\".* FROM \"event_type_versions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, eventTypeVersionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EventTypeVersionSlice")
	}

	*o = slice

	return nil
}

// EventTypeVersionExists checks if the EventTypeVersion row exists.
func EventTypeVersionExists(ctx context.Context, exec boil.ContextExecutor, eventTypeAction string, version int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"event_type_versions\" where \"event_type_action\"=$1 AND \"version\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, eventTypeAction, version)
	}
	row := exec.QueryRowContext(ctx, sql, eventTypeAction, version)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if event_type_versions exists")
	}

	return exists, nil
}

// Exists checks if the EventTypeVersion row exists.
func (o *EventTypeVersion) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EventTypeVersionExists(ctx, exec, o.EventTypeAction, o.Version)
}
