// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	TokenAuthScopes  = "TokenAuth.Scopes"
)

// Actor defines model for Actor.
type Actor struct {
	ActorType string                  `json:"actor_type"`
	Id        string                  `json:"id"`
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	Name      *string                 `json:"name,omitempty"`
}

// Context defines model for Context.
type Context struct {
	Location  string  `json:"location"`
	UserAgent *string `json:"user_agent,omitempty"`
}

// ErrorSchema defines model for ErrorSchema.
type ErrorSchema struct {
	// Error Error custom error code such as 'email_in_use'
	Error string `json:"error"`

	// Message A description about the error
	Message string `json:"message"`
}

// Event defines model for Event.
type Event struct {
	Id         string                  `json:"id"`
	SourceId   string                  `json:"source_id"`
	Version    int                     `json:"version"`
	Targets    []Target                `json:"targets"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	OccurredAt string                  `json:"occurred_at"`
	Actor      Actor                   `json:"actor"`
	Context    Context                 `json:"context"`
}

// EventList defines model for EventList.
type EventList struct {
	Data           []Event `json:"data"`
	LastItemCursor string  `json:"last_item_cursor"`
}

// EventType defines model for EventType.
type EventType struct {
	Action                       string    `json:"action"`
	CreatedAt                    time.Time `json:"created_at"`
	Id                           string    `json:"id"`
	Schema                       *string   `json:"schema,omitempty"`
	ShouldValidateMetadataSchema bool      `json:"should_validate_metadata_schema"`
	TargetTypes                  []string  `json:"target_types"`
	UpdatedAt                    time.Time `json:"updated_at"`
	Version                      int       `json:"version"`
}

// EventTypeList defines model for EventTypeList.
type EventTypeList struct {
	Data       []EventType `json:"data"`
	Pagination Pagination  `json:"pagination"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Total       int `json:"total"`
	PerPage     int `json:"per_page"`
	CurrentPage int `json:"current_page"`
	TotalPages  int `json:"total_pages"`
}

// Source defines model for Source.
type Source struct {
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SourceList defines model for SourceList.
type SourceList struct {
	Data       []Source   `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Target defines model for Target.
type Target struct {
	Id         string                  `json:"id"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Name       *string                 `json:"name,omitempty"`
	TargetType string                  `json:"target_type"`
}

// Token defines model for Token.
type Token struct {
	Id        string    `json:"id"`
	Value     string    `json:"value"`
	Name      string    `json:"name"`
	SourceId  string    `json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
}

// EventId defines model for event_id.
type EventId = string

// EventTypeAction defines model for event_type_action.
type EventTypeAction = string

// PaginationLimit defines model for pagination_limit.
type PaginationLimit = int

// PaginationPage defines model for pagination_page.
type PaginationPage = int

// SourceId defines model for source_id.
type SourceId = string

// SourceIdQuery defines model for source_id_query.
type SourceIdQuery = string

// StartFromCursor defines model for start_from_cursor.
type StartFromCursor = string

// TokenId defines model for token_id.
type TokenId = string

// XToken defines model for x_token.
type XToken = string

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorSchema

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorSchema

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorSchema

// CreateEventJSONBody defines parameters for CreateEvent.
type CreateEventJSONBody struct {
	Actor struct {
		Id       string                  `json:"id"`
		Metadata *map[string]interface{} `json:"metadata,omitempty"`
		Name     *string                 `json:"name,omitempty"`
		Type     string                  `json:"type"`
	} `json:"actor"`
	Context struct {
		Location  string  `json:"location"`
		UserAgent *string `json:"user_agent,omitempty"`
	} `json:"context"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	OccurredAt time.Time               `json:"occurred_at"`
	SourceId   string                  `json:"source_id"`
	Targets    []struct {
		Id       string                  `json:"id"`
		Metadata *map[string]interface{} `json:"metadata,omitempty"`
		Name     *string                 `json:"name,omitempty"`
		Type     string                  `json:"type"`
	} `json:"targets"`
	Version int `json:"version"`
}

// CreateEventParams defines parameters for CreateEvent.
type CreateEventParams struct {
	XToken XToken `json:"x-token"`
}

// CreateEventTypeJSONBody defines parameters for CreateEventType.
type CreateEventTypeJSONBody struct {
	Action                       string   `json:"action"`
	Schema                       *string  `json:"schema,omitempty"`
	ShouldValidateMetadataSchema bool     `json:"should_validate_metadata_schema"`
	TargetTypes                  []string `json:"target_types"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	SourceId SourceIdQuery `form:"source_id" json:"source_id"`

	// StartFrom Opaque cursor returned by the previous page. Omit to start from the most recent event.
	StartFrom *StartFromCursor `form:"start_from,omitempty" json:"start_from,omitempty"`

	// Limit The number of items per page
	Limit *PaginationLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSourcesParams defines parameters for GetSources.
type GetSourcesParams struct {
	// Limit The number of items per page
	Limit *PaginationLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Page The page number
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`
}

// CreateSourceJSONBody defines parameters for CreateSource.
type CreateSourceJSONBody struct {
	Name string `json:"name"`
}

// CreateTokenJSONBody defines parameters for CreateToken.
type CreateTokenJSONBody struct {
	Name string `json:"name"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody CreateEventJSONBody

// CreateEventTypeJSONRequestBody defines body for CreateEventType for application/json ContentType.
type CreateEventTypeJSONRequestBody CreateEventTypeJSONBody

// CreateSourceJSONRequestBody defines body for CreateSource for application/json ContentType.
type CreateSourceJSONRequestBody CreateSourceJSONBody

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody CreateTokenJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create an event
	// (POST /v1/events)
	CreateEvent(ctx echo.Context, params CreateEventParams) error
	// List event types
	// (GET /x/v1/event-types)
	GetEventTypes(ctx echo.Context) error
	// Create an event type
	// (POST /x/v1/event-types)
	CreateEventType(ctx echo.Context) error
	// Archive an event
	// (POST /x/v1/event-types/{event_id}/archive)
	ArchiveEventType(ctx echo.Context, eventId EventId) error
	// Return the details of an Event Type
	// (GET /x/v1/event-types/{event_type_action})
	GetEventTypeByID(ctx echo.Context, eventTypeAction EventTypeAction) error
	// Get events
	// (GET /x/v1/events)
	GetEvents(ctx echo.Context, params GetEventsParams) error
	// List all sources
	// (GET /x/v1/sources)
	GetSources(ctx echo.Context, params GetSourcesParams) error
	// Create a source
	// (POST /x/v1/sources)
	CreateSource(ctx echo.Context) error
	// Get source details
	// (GET /x/v1/sources/{source_id})
	GetSourceByID(ctx echo.Context, sourceId SourceId) error
	// Create token
	// (POST /x/v1/sources/{source_id}/token)
	CreateToken(ctx echo.Context, sourceId SourceId) error
	// Delete token
	// (DELETE /x/v1/sources/{source_id}/token/{token_id})
	DeleteToken(ctx echo.Context, sourceId SourceId, tokenId TokenId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateEvent converts echo context to params.
func (w *ServerInterfaceWrapper) CreateEvent(ctx echo.Context) error {
	var err error

	ctx.Set(TokenAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateEventParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "x-token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-token")]; found {
		var XToken XToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-token, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-token", valueList[0], &XToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-token: %s", err))
		}

		params.XToken = XToken
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter x-token is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateEvent(ctx, params)
	return err
}

// GetEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypes(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventTypes(ctx)
	return err
}

// CreateEventType converts echo context to params.
func (w *ServerInterfaceWrapper) CreateEventType(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateEventType(ctx)
	return err
}

// ArchiveEventType converts echo context to params.
func (w *ServerInterfaceWrapper) ArchiveEventType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "event_id" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "event_id", ctx.Param("event_id"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter event_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ArchiveEventType(ctx, eventId)
	return err
}

// GetEventTypeByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypeByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "event_type_action" -------------
	var eventTypeAction EventTypeAction

	err = runtime.BindStyledParameterWithOptions("simple", "event_type_action", ctx.Param("event_type_action"), &eventTypeAction, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter event_type_action: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventTypeByID(ctx, eventTypeAction)
	return err
}

// GetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvents(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams
	// ------------- Required query parameter "source_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "source_id", ctx.QueryParams(), &params.SourceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Optional query parameter "start_from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start_from", ctx.QueryParams(), &params.StartFrom, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_from: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvents(ctx, params)
	return err
}

// GetSources converts echo context to params.
func (w *ServerInterfaceWrapper) GetSources(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSourcesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSources(ctx, params)
	return err
}

// CreateSource converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSource(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSource(ctx)
	return err
}

// GetSourceByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetSourceByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSourceByID(ctx, sourceId)
	return err
}

// CreateToken converts echo context to params.
func (w *ServerInterfaceWrapper) CreateToken(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateToken(ctx, sourceId)
	return err
}

// DeleteToken converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteToken(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "token_id" -------------
	var tokenId TokenId

	err = runtime.BindStyledParameterWithOptions("simple", "token_id", ctx.Param("token_id"), &tokenId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter token_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteToken(ctx, sourceId, tokenId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/v1/events", wrapper.CreateEvent)
	router.GET(baseURL+"/x/v1/event-types", wrapper.GetEventTypes)
	router.POST(baseURL+"/x/v1/event-types", wrapper.CreateEventType)
	router.POST(baseURL+"/x/v1/event-types/:event_id/archive", wrapper.ArchiveEventType)
	router.GET(baseURL+"/x/v1/event-types/:event_type_action", wrapper.GetEventTypeByID)
	router.GET(baseURL+"/x/v1/events", wrapper.GetEvents)
	router.GET(baseURL+"/x/v1/sources", wrapper.GetSources)
	router.POST(baseURL+"/x/v1/sources", wrapper.CreateSource)
	router.GET(baseURL+"/x/v1/sources/:source_id", wrapper.GetSourceByID)
	router.POST(baseURL+"/x/v1/sources/:source_id/token", wrapper.CreateToken)
	router.DELETE(baseURL+"/x/v1/sources/:source_id/token/:token_id", wrapper.DeleteToken)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RaW4/bNhb+KwR3gb5oLE+TBQo/rZOZFrPbNoOMgX0IBgYtHdvsSqTCizvGwP+94EU3",
	"i7Itx3HSN8skD8/lO1fpFSc8LzgDpiSevOKCCJKDAmGfYANMzWlqflOGJ7ggao0jzEgOeFIvR1jAZ00F",
	"pHiihIYIy2QNOTHn1LYwe6USlK3wbhf5Y+b/OUkU5ewg+ea+YfcUZEUZMQfniRaSC7MtBZkIWrhr8YeC",
	"fNaA3DISoLRgkKLFFqk1oELAhnItUUFWMEIfcqqQ4kgqIhRaCp7bXTmXCglIgClkWR7hyInzWYPY1vJ4",
	"Jk5mOqM5VV2eZ2tATOcLEIgvEVWQS1SAsEz23OwoNS/OyQvNdY4nt+NxhHPK/FNUskSZghWIfZ7sJUGW",
	"zIrnq4cLz2CDicPXSq5FAv3wq9eH4aI6N3cMltT32D2XvOL/B9bPdbU8jOrL3B6siK6BpFbTnuzLjVsf",
	"QnVnNsuCMwnW3d+R9CN81iDVvRDOXRLOFDCLQlIUGU0sDOI/pPPamvY/BSzxBP8jruNJ7FZlbKk9ua32",
	"1jZ67ogiaEMymlriCOzluwg/MAWCkewJxAbEVXmaohUwEDRx3KBST4at37n6mWuWXpWhj+DwiBhXaGmu",
	"d1h2pw3xaaIcO4XgBQhFnVGJ+XvuTN+BQIQdTjt/56BISpTlmqQpNVyQ7LFB2YGL6SwjiwzKZ0+IL/6A",
	"RBlCDp4hRNc4/YStOzQ49eeedxF+b5T7orqCZdzpOci/liDmZOWt0sNlDzMVYXN90ywdFqBEQNtW9gxK",
	"tFQ89/hJeApI6mSNiEQ/QE5oNqdsriX8gKOQ+qUMRtopajwjsuBa2STkODkmWbmrJP8cMNj9xistAKNj",
	"GHYQ3EXOI5zRDu0vbXsFHPIk0UJAOieWqyUXufmFDfEbRXMImaGVgTqriogVuLLJZuFj0s7sfnvSkSJC",
	"kK153oCQbSQ382DHUZqZqTzq3QfXbNVWaEv/XBr5SQkgedfUdbHU/p95ix7zJhO7vMlO0otDXEcte5Jb",
	"klHJXCXEzAe2Dlr7IkMigKggDqAXBz0A6M2sEZZrrrN07rMazEsczztnFpxnQFgNKBsB26jqQm8PQLpI",
	"Bws1EHRVCV4jrsXvcZlbum/x3LLmr1QG4s9wRFlkBHRVV7PHyDzWO3vQ2KBlZHhske54lTD9TFlB7+k8",
	"wi83XJiSbvLGMAnihJ0/2nJTkezwtttymyUpD29+uy+qu6DBUtSWpU3bqOHJxqeACoa63p5SQm64J2a4",
	"3NhT2WBvOaQe6xz22gP4DiQkp6QLgN1r+7pI97msw/k3KidbsejEcrN5olFvzso263LY/deFsPvmcEnS",
	"QmmENyTTx3whpBd3rsJ0s9hoKOHZdh+QaEHV1tbHvocEIkBMtVqbp4V9+rnU1n/+NysHADb12dVac2ul",
	"ClyaoCRxpNstMV/Q/8LWFR/w4trGO57IbgVtLpGTOF5RtdaLUcLzeElFThlP1oStCKMx0SlVkMYf76d3",
	"v92PciO6Ftmgw7ZsYEte9ockscCxlT+eYH9qVB7798osGIK424s+PiABSxDAEkBLLpC/A00fH3CEM5qA",
	"aU1NaebU89vD7AyW418f3t///mQFNh4FIpcflqb5pgkMEz7CiqrMGqb6p6o38Hg0Ht3aorwARgqKJ/jN",
	"aDx6Y8OMWlujxZvb2E7T3FiSy8AkbDQaYUtE2MD0kOIJfm8h6krKqDXO/BQOgfWWuJyx7J6dW4BU73i6",
	"HdTi93RNF42SA6LigHBotoQSVXKBBvzUhjtw/dlKOdDxwQU7vr+xZc9vQ7+0A23TM7LvzyJ/HL8NDFaM",
	"WyOfhZDUSQJSLnWWbV3UXBKd9Q4dKvJxaK7YTGc2VjSS0KdnExGkznMitlWMQYS5eb+VeGUiDH7Ui4wm",
	"Ni7bBBm/VHHspmrrfOHUFs0Ugo4cKvupdmD7BVTV1kjc0dbt5QaRrUYsOBvNDLN82eJ3F+G34/Fx5e8P",
	"mS9uuGYFsm+5gJZL003TnDJvuagn4ZSGRwz+bJA5lIRmbv1i6aQv3n4vs4i9QFFNDQbOCk4LEV8B9CHA",
	"2zdu8Ge2rUJPw/Z/C9zvRawStSHsh6JW/Fq+6t3FRCRruoH+qmzqNjTDY9s7/Iamewyr06r3zq5QOy1r",
	"rIlECwCGvADd/PH9mzGg2qEmbLxO3/Umo4/2Rbh9sZCCIjSTJtoThpwqZ6GY18xP77YPd2datfm6P2De",
	"8fU8/jI+/tYh8vC59hvFi0CqwsxptjwOo/7SJdSGlWiQg2Gw/3Z+Fx090v3QY9gh93nE10ebf+ESwJuz",
	"hbTrSEvKVv6blJsFkZCimtnRdSPOL+DrJXkMJM5ug1Hy5I8NhUnXfINMbifXX9XijflusIb2zEBaVdOl",
	"Bq9fEZMsq24fVhH3j2D8WPpSpe9p3xH4Ke7J7eUFLR2yslu5UsN6Sv3nrXyiL8evVTDenefXZxUC9XDh",
	"Cg4a/tamSpmyernyrRL5kEjtPxHyef4MK8fVR2ZD3X3m5/FfZurvMlJcrst0SgrVm2bh+4kT1cuVs+AT",
	"v5bfOO4cgjJQcBqW7uzeL8bS8VKg+grztBbS2cdJ8i3t4/Rz2D6WnqHvtFa/BZrEccYTkq25VJOfxj+N",
	"8e5591cAAAD//44Sy0gBLgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
