// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	TokenAuthScopes  = "TokenAuth.Scopes"
)

// Actor defines model for Actor.
type Actor struct {
	ActorType string                  `json:"actor_type"`
	Id        string                  `json:"id"`
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	Name      *string                 `json:"name,omitempty"`
}

// Context defines model for Context.
type Context struct {
	Location  string  `json:"location"`
	UserAgent *string `json:"user_agent,omitempty"`
}

// ErrorSchema defines model for ErrorSchema.
type ErrorSchema struct {
	// Error Error custom error code such as 'email_in_use'
	Error string `json:"error"`

	// Message A description about the error
	Message string `json:"message"`
}

// Event defines model for Event.
type Event struct {
	Id         string                  `json:"id"`
	SourceId   string                  `json:"source_id"`
	Action     string                  `json:"action"`
	Version    int                     `json:"version"`
	Targets    []Target                `json:"targets"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	OccurredAt string                  `json:"occurred_at"`
	Actor      Actor                   `json:"actor"`
	Context    Context                 `json:"context"`
}

// EventList defines model for EventList.
type EventList struct {
	Data    []Event `json:"data"`
	HasMore bool    `json:"has_more"`
}

// EventType defines model for EventType.
type EventType struct {
	Action                       string                 `json:"action"`
	Version                      int                    `json:"version"`
	ShouldValidateMetadataSchema bool                   `json:"should_validate_metadata_schema"`
	Schema                       map[string]interface{} `json:"schema"`
	TargetTypes                  []string               `json:"target_types"`
	CreatedAt                    time.Time              `json:"created_at"`
}

// EventTypeList defines model for EventTypeList.
type EventTypeList struct {
	Data       []EventType `json:"data"`
	Pagination Pagination  `json:"pagination"`
}

// EventTypeNonPaginatedList defines model for EventTypeNonPaginatedList.
type EventTypeNonPaginatedList struct {
	Data []EventType `json:"data"`
}

// LogIn defines model for LogIn.
type LogIn struct {
	Jwt string `json:"jwt"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Total       int `json:"total"`
	PerPage     int `json:"per_page"`
	CurrentPage int `json:"current_page"`
	TotalPages  int `json:"total_pages"`
}

// Source defines model for Source.
type Source struct {
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SourceList defines model for SourceList.
type SourceList struct {
	Data       []Source   `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Target defines model for Target.
type Target struct {
	Id         string                  `json:"id"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Name       *string                 `json:"name,omitempty"`
	TargetType string                  `json:"target_type"`
}

// Token defines model for Token.
type Token struct {
	Id        string    `json:"id"`
	Value     string    `json:"value"`
	Name      string    `json:"name"`
	SourceId  string    `json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
}

// TokenList defines model for TokenList.
type TokenList struct {
	Data []Token `json:"data"`
}

// User defines model for User.
type User struct {
	Id    string `json:"id"`
	Email string `json:"email"`
	Role  string `json:"role"`
}

// Action defines model for action.
type Action = string

// ActionFilter defines model for action_filter.
type ActionFilter = string

// EndingBefore defines model for ending_before.
type EndingBefore = string

// EventId defines model for event_id.
type EventId = string

// EventsByAction defines model for events_by_action.
type EventsByAction = string

// EventsByActorId defines model for events_by_actor_id.
type EventsByActorId = string

// EventsByActorName defines model for events_by_actor_name.
type EventsByActorName = string

// EventsByTargetId defines model for events_by_target_id.
type EventsByTargetId = string

// EventsEndDate defines model for events_end_date.
type EventsEndDate = time.Time

// EventsStartDate defines model for events_start_date.
type EventsStartDate = time.Time

// NameFilter defines model for name_filter.
type NameFilter = string

// PaginationLimit defines model for pagination_limit.
type PaginationLimit = int

// PaginationPage defines model for pagination_page.
type PaginationPage = int

// SourceId defines model for source_id.
type SourceId = string

// SourceIdQuery defines model for source_id_query.
type SourceIdQuery = string

// StartingAfter defines model for starting_after.
type StartingAfter = string

// TokenId defines model for token_id.
type TokenId = string

// XToken defines model for x_token.
type XToken = string

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorSchema

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorSchema

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorSchema

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = ErrorSchema

// CreateEventJSONBody defines parameters for CreateEvent.
type CreateEventJSONBody struct {
	// Action Event type action
	Action string `json:"action"`
	Actor  struct {
		Id       string                  `json:"id"`
		Metadata *map[string]interface{} `json:"metadata,omitempty"`
		Name     *string                 `json:"name,omitempty"`
		Type     string                  `json:"type"`
	} `json:"actor"`
	Context struct {
		Location  string  `json:"location"`
		UserAgent *string `json:"user_agent,omitempty"`
	} `json:"context"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	OccurredAt time.Time               `json:"occurred_at"`
	SourceId   string                  `json:"source_id"`
	Targets    []struct {
		Id       string                  `json:"id"`
		Metadata *map[string]interface{} `json:"metadata,omitempty"`
		Name     *string                 `json:"name,omitempty"`
		Type     string                  `json:"type"`
	} `json:"targets"`
	Version int `json:"version"`
}

// CreateEventParams defines parameters for CreateEvent.
type CreateEventParams struct {
	XToken XToken `json:"x-token"`
}

// GetEventTypesParams defines parameters for GetEventTypes.
type GetEventTypesParams struct {
	// Limit The number of items per page
	Limit *PaginationLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Page The page number
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// Action Action filter
	Action *ActionFilter `form:"action,omitempty" json:"action,omitempty"`
}

// CreateEventTypeJSONBody defines parameters for CreateEventType.
type CreateEventTypeJSONBody struct {
	Action                       string   `json:"action"`
	Schema                       *string  `json:"schema,omitempty"`
	ShouldValidateMetadataSchema bool     `json:"should_validate_metadata_schema"`
	TargetTypes                  []string `json:"target_types"`
}

// CreateEventTypeVersionJSONBody defines parameters for CreateEventTypeVersion.
type CreateEventTypeVersionJSONBody struct {
	Schema      *string  `json:"schema,omitempty"`
	TargetTypes []string `json:"target_types"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	SourceId SourceIdQuery `form:"source_id" json:"source_id"`

	// StartingAfter A cursor for use in pagination. starting_after is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include starting_after=obj_foo in order to fetch the next page of the list.
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore A cursor for use in pagination. ending_before is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with obj_bar, your subsequent call can include ending_before=obj_bar in order to fetch the previous page of the list.
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`

	// Limit The number of items per page
	Limit     *PaginationLimit   `form:"limit,omitempty" json:"limit,omitempty"`
	Action    *EventsByAction    `form:"action,omitempty" json:"action,omitempty"`
	ActorId   *EventsByActorId   `form:"actor_id,omitempty" json:"actor_id,omitempty"`
	ActorName *EventsByActorName `form:"actor_name,omitempty" json:"actor_name,omitempty"`
	TargetId  *EventsByTargetId  `form:"target_id,omitempty" json:"target_id,omitempty"`
	StartDate *EventsStartDate   `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate   *EventsEndDate     `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// LogInJSONBody defines parameters for LogIn.
type LogInJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetSourcesParams defines parameters for GetSources.
type GetSourcesParams struct {
	// Limit The number of items per page
	Limit *PaginationLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Page The page number
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`

	// Name Name filter
	Name *NameFilter `form:"name,omitempty" json:"name,omitempty"`
}

// CreateSourceJSONBody defines parameters for CreateSource.
type CreateSourceJSONBody struct {
	Name string `json:"name"`
}

// CreateTokenJSONBody defines parameters for CreateToken.
type CreateTokenJSONBody struct {
	Name string `json:"name"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody CreateEventJSONBody

// CreateEventTypeJSONRequestBody defines body for CreateEventType for application/json ContentType.
type CreateEventTypeJSONRequestBody CreateEventTypeJSONBody

// CreateEventTypeVersionJSONRequestBody defines body for CreateEventTypeVersion for application/json ContentType.
type CreateEventTypeVersionJSONRequestBody CreateEventTypeVersionJSONBody

// LogInJSONRequestBody defines body for LogIn for application/json ContentType.
type LogInJSONRequestBody LogInJSONBody

// CreateSourceJSONRequestBody defines body for CreateSource for application/json ContentType.
type CreateSourceJSONRequestBody CreateSourceJSONBody

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody CreateTokenJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create an event
	// (POST /v1/events)
	CreateEvent(ctx echo.Context, params CreateEventParams) error
	// List event types
	// (GET /x/v1/event-types)
	GetEventTypes(ctx echo.Context, params GetEventTypesParams) error
	// Create an event type
	// (POST /x/v1/event-types)
	CreateEventType(ctx echo.Context) error
	// Delete event an event type
	// (DELETE /x/v1/event-types/{action})
	DeleteEventType(ctx echo.Context, action Action) error
	// Return the details of an Event Type
	// (GET /x/v1/event-types/{action})
	GetEventTypeByID(ctx echo.Context, action Action) error
	// Rollback event type version
	// (DELETE /x/v1/event-types/{action}/versions)
	RollbackEventTypeVersion(ctx echo.Context, action Action) error
	// List all versions of an event types
	// (GET /x/v1/event-types/{action}/versions)
	GetEventTypeVersions(ctx echo.Context, action Action) error
	// Create an event type version
	// (POST /x/v1/event-types/{action}/versions)
	CreateEventTypeVersion(ctx echo.Context, action Action) error
	// Get events
	// (GET /x/v1/events)
	GetEvents(ctx echo.Context, params GetEventsParams) error
	// Get event by id
	// (GET /x/v1/events/{event_id})
	GetEventByID(ctx echo.Context, eventId EventId) error
	// Log in
	// (POST /x/v1/login)
	LogIn(ctx echo.Context) error
	// Return the user details of the authenticated.
	// (GET /x/v1/profile)
	GetUserProfile(ctx echo.Context) error
	// List all sources
	// (GET /x/v1/sources)
	GetSources(ctx echo.Context, params GetSourcesParams) error
	// Create a source
	// (POST /x/v1/sources)
	CreateSource(ctx echo.Context) error
	// Get source details
	// (GET /x/v1/sources/{source_id})
	GetSourceByID(ctx echo.Context, sourceId SourceId) error
	// List tokens
	// (GET /x/v1/sources/{source_id}/tokens)
	GetTokens(ctx echo.Context, sourceId SourceId) error
	// Create token
	// (POST /x/v1/sources/{source_id}/tokens)
	CreateToken(ctx echo.Context, sourceId SourceId) error
	// Delete token
	// (DELETE /x/v1/sources/{source_id}/tokens/{token_id})
	DeleteToken(ctx echo.Context, sourceId SourceId, tokenId TokenId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateEvent converts echo context to params.
func (w *ServerInterfaceWrapper) CreateEvent(ctx echo.Context) error {
	var err error

	ctx.Set(TokenAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateEventParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "x-token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-token")]; found {
		var XToken XToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-token, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-token", valueList[0], &XToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-token: %s", err))
		}

		params.XToken = XToken
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter x-token is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateEvent(ctx, params)
	return err
}

// GetEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypes(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventTypesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", ctx.QueryParams(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter action: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventTypes(ctx, params)
	return err
}

// CreateEventType converts echo context to params.
func (w *ServerInterfaceWrapper) CreateEventType(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateEventType(ctx)
	return err
}

// DeleteEventType converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteEventType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "action" -------------
	var action Action

	err = runtime.BindStyledParameterWithOptions("simple", "action", ctx.Param("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter action: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteEventType(ctx, action)
	return err
}

// GetEventTypeByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypeByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "action" -------------
	var action Action

	err = runtime.BindStyledParameterWithOptions("simple", "action", ctx.Param("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter action: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventTypeByID(ctx, action)
	return err
}

// RollbackEventTypeVersion converts echo context to params.
func (w *ServerInterfaceWrapper) RollbackEventTypeVersion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "action" -------------
	var action Action

	err = runtime.BindStyledParameterWithOptions("simple", "action", ctx.Param("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter action: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RollbackEventTypeVersion(ctx, action)
	return err
}

// GetEventTypeVersions converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypeVersions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "action" -------------
	var action Action

	err = runtime.BindStyledParameterWithOptions("simple", "action", ctx.Param("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter action: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventTypeVersions(ctx, action)
	return err
}

// CreateEventTypeVersion converts echo context to params.
func (w *ServerInterfaceWrapper) CreateEventTypeVersion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "action" -------------
	var action Action

	err = runtime.BindStyledParameterWithOptions("simple", "action", ctx.Param("action"), &action, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter action: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateEventTypeVersion(ctx, action)
	return err
}

// GetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvents(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams
	// ------------- Required query parameter "source_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "source_id", ctx.QueryParams(), &params.SourceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "starting_after", ctx.QueryParams(), &params.StartingAfter, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter starting_after: %s", err))
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ending_before", ctx.QueryParams(), &params.EndingBefore, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ending_before: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", ctx.QueryParams(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter action: %s", err))
	}

	// ------------- Optional query parameter "actor_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor_id", ctx.QueryParams(), &params.ActorId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter actor_id: %s", err))
	}

	// ------------- Optional query parameter "actor_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor_name", ctx.QueryParams(), &params.ActorName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter actor_name: %s", err))
	}

	// ------------- Optional query parameter "target_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "target_id", ctx.QueryParams(), &params.TargetId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter target_id: %s", err))
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "start_date", ctx.QueryParams(), &params.StartDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_date: %s", err))
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "end_date", ctx.QueryParams(), &params.EndDate, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end_date: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvents(ctx, params)
	return err
}

// GetEventByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "event_id" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "event_id", ctx.Param("event_id"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter event_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventByID(ctx, eventId)
	return err
}

// LogIn converts echo context to params.
func (w *ServerInterfaceWrapper) LogIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LogIn(ctx)
	return err
}

// GetUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserProfile(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetUserProfile(ctx)
	return err
}

// GetSources converts echo context to params.
func (w *ServerInterfaceWrapper) GetSources(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSourcesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "name", ctx.QueryParams(), &params.Name, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSources(ctx, params)
	return err
}

// CreateSource converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSource(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSource(ctx)
	return err
}

// GetSourceByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetSourceByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSourceByID(ctx, sourceId)
	return err
}

// GetTokens converts echo context to params.
func (w *ServerInterfaceWrapper) GetTokens(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTokens(ctx, sourceId)
	return err
}

// CreateToken converts echo context to params.
func (w *ServerInterfaceWrapper) CreateToken(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateToken(ctx, sourceId)
	return err
}

// DeleteToken converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteToken(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "token_id" -------------
	var tokenId TokenId

	err = runtime.BindStyledParameterWithOptions("simple", "token_id", ctx.Param("token_id"), &tokenId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter token_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteToken(ctx, sourceId, tokenId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/v1/events", wrapper.CreateEvent)
	router.GET(baseURL+"/x/v1/event-types", wrapper.GetEventTypes)
	router.POST(baseURL+"/x/v1/event-types", wrapper.CreateEventType)
	router.DELETE(baseURL+"/x/v1/event-types/:action", wrapper.DeleteEventType)
	router.GET(baseURL+"/x/v1/event-types/:action", wrapper.GetEventTypeByID)
	router.DELETE(baseURL+"/x/v1/event-types/:action/versions", wrapper.RollbackEventTypeVersion)
	router.GET(baseURL+"/x/v1/event-types/:action/versions", wrapper.GetEventTypeVersions)
	router.POST(baseURL+"/x/v1/event-types/:action/versions", wrapper.CreateEventTypeVersion)
	router.GET(baseURL+"/x/v1/events", wrapper.GetEvents)
	router.GET(baseURL+"/x/v1/events/:event_id", wrapper.GetEventByID)
	router.POST(baseURL+"/x/v1/login", wrapper.LogIn)
	router.GET(baseURL+"/x/v1/profile", wrapper.GetUserProfile)
	router.GET(baseURL+"/x/v1/sources", wrapper.GetSources)
	router.POST(baseURL+"/x/v1/sources", wrapper.CreateSource)
	router.GET(baseURL+"/x/v1/sources/:source_id", wrapper.GetSourceByID)
	router.GET(baseURL+"/x/v1/sources/:source_id/tokens", wrapper.GetTokens)
	router.POST(baseURL+"/x/v1/sources/:source_id/tokens", wrapper.CreateToken)
	router.DELETE(baseURL+"/x/v1/sources/:source_id/tokens/:token_id", wrapper.DeleteToken)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xbX2/jNhL/KoTugL5oLae77RUGClzabIvctXvBJtt7WAQGLY1t7lKkS1JOfIG/+4F/",
	"JFMWZUuOkt30LQ7JmeHMb/5wSD1EKc9XnAFTMpo8RCsscA4KhPmFU0U4038RFk2iFVbLKI4YziGalINx",
	"JODPggjIookSBcSRTJeQY71KbVZ6plSCsEW03cZu0XROqAKhp2QgU0FWlk90boaRG44t2z8LEJsA30N8",
	"gGWELaYzmHMBAT4oLYTkAs25QIUERBha4QVhWE8YodpyRCTCDPHZJ0gVurxAaokVymBOGEi04YVAK4pT",
	"Q0QtAVEi1Qj9wgUiTCrMUogRmeuJKMefAWEzA2m1gVQIswwJSIGsAZ2Nx46PjJFUWCjCFuiOqKX+93SG",
	"RWwZymIm9XqmUIopRSlmiLCUFhnUhf/RrdPCcZGBQIqjOah0aWRdCVgTXki9e0B8vttAi/brij1ihDUw",
	"NSVZC4Cq4X4QMsvkdLaZ7sHzJJz4xLjwhW2Ss+P9CNrVh0iaH12JKiwWoA6IuZvQiSSwbJph1SpiNe5T",
	"m3ORYxVNIj3yShEjfysLA+ODTLwZJ7DRRFoDyjucw+Fw0kH9u8gwpSQnqsnmZgmIFfkMhPYhoiCXaAXC",
	"eFULX0vJZ5zje5IXeTQ5G4/jKCfM/ao2TZiCBYh9mQyToEjGqa1cLVI4AT0hDrOVvBAptPv0bryfU1fr",
	"plbANqScSt6F0imeh/POkXxQX/+lEoKNvbt0MOe8Qzqoy/6jW9iSDxjcq865YE+rh02g+Gdg7cCphvsZ",
	"9n5qFlZEl4AzI4oje//KjvehutWT5YozCaYK+gln761p3grBDXpSzhQwEwjwakVJanCSfJI2He1o/13A",
	"PJpEf0t2ZVZiR2ViqF3bqYZrHZMXWGG0xpRkhjgCw3wbR5dMgWCYXoNYg3hWmc7RAhgIklppUKknLdY7",
	"rn7hBcueVaD3YEMCYlyhuWavRfnAcKGWXJD/wfOK80EWmNINSnEhQaLZRscJLQsw5RgiA0iUEymr6GSJ",
	"a97nuiQwhbjgKxCKQFmIczG1QG0ANo6sVzX+nYPCGVZmUzjLiGaP6ZVH2boCKyjFMwrlb0fIxp1oWzpT",
	"yP92XvUxMs7rSXq7jaOftdLvVXNHlFt1BAUvJIgpXjhrtYjXIkVFWLP3zdUQAUpk1G1o1qC0kIrnDuYp",
	"13G0SJcIS/QN5JjQKWHTQsI3zZJE613KYE4+R95vhGe8UCbIWkmO7aycVZK/DVjq7doprYGfoK7j6P6V",
	"yQLR5PXWGe+YC1iIbmPrUNa2h+aXEGjBqSfC2WCY9Yh+v40jnqaFEJBNsdovLHG4sPQI/GO/7Gmd+a1O",
	"c6b+Nko3ZeAx7dyY+Vo5jiwWAm98qt9t42gNQtYNWBZl3sQ3QYf0S6bqSFTSK02+k3tn1rrabktw/UZk",
	"AGClyTrt2YJ0f8vbOFpiOc3dgd2NzTingFnDGQxDb0Ul340Lkr0dQKMvFYBVECdwFCffb/2i4hB2W7H6",
	"RpNY8oJmU5f4YVo6xLRRsJSq2XNidwLUk+owbMSpRyPu232r7M7cR3ZRqcrHYk3ymjFq1h0KgQYpARTu",
	"Cv9jZK52M1vw6dGq7eEdZ24xZE+7n5BcWpTf+OKSNdl+ulPHM72epGlc1TRVJ2RCB1PV6bQdRRq0KxAd",
	"ZpoAyxWmh6edldMMSdkzaloGnkhxfS912loN1ybEBlTwiGjyulu6DFdmeyorVtnJcoSTimuaeBuscQlV",
	"JlZJA2Ddaft5Hdel6YbkX6jyrsXKjpW5v8JsqTw4Dwfa7wYC7evOJZfOmGtMi2NOEFKIXVeB2S+U9lKP",
	"UdUA0LUq7xyiP0gInAXN8eOoz3cwg+D0mBlCarP83fKmp2vTQVoIojbm4OV6KIAFiPNCLfWvmfn1S4mt",
	"f/33piwITF1jRnc4Wyq1ikorlCSOdHtKBa/Iv2FjT+pwb9smFzyVzaOZZiInSbIgalnMRinPkwUoXGRE",
	"QZbBOnF/Ju/fnl/8/naUa1UUgvZYak5AbM7LZgROlWfPaE5EThgfpUvMFpiRfy70gCYXNfswV5dIwBwE",
	"sBRM09LxQOdXl1EcUZICk8a6TjW/X970Fjj57fLnt++uzWY1aEHk8j/zaxBrkkKfjceRIooag1T/qQrM",
	"aDwaj840A74ChlckmkSvR+PRaxOF1dIYK1mfJfY+wTgEl4Em/Gg0igwRYeL2ZRZNop+NI9sDR1y73fwY",
	"dtXdlKTsLW5vrReAVD/xbNOrl9R2CtlrOWj5kMYsqiroRsTH4dbQIzNQj4zTI9WYHBMgng7QDura/gmw",
	"P1kpBxoIbTdTBzNYS6PgBVt2vxbzzo8ZzHFBVduVks/Dz8G1HkXfZkWdsFbIflf/2/GbNkd02R/JIk1B",
	"ynlB6cbGYLeRcOioyCehDr2fGE308dLZx1sdY2SR51hsqqiFMEPgIpfCCx2zoqtiRklqovytppjcV5Hx",
	"VXXid5VqfWu6fLHkUHnArofKX0FVx0jZO1g27ki3cZ815mTVYUn9/YiNzDWjjodr9df6DcHLEHNtx+c1",
	"tW7j6I2V4jBG9m+VBseXX3LtAywAhhJh51lOmANY3JJpS3wiBncemUPZ98aOD51Hm0G37VrvlM7a6d20",
	"1sbYXo/rmEzdItnZ8KAPAd68coA7uqkipGf7F4H7vcBaojaE/VBwTR6sHbfWJSio0CWPSJdk3WRSd40L",
	"s9p3jX7x1gEqEAFb09oSSzQDYLW8huw2spdhP6s1p9cuVozDyfA9qELYxxkZKEyo1GEcM2Q1dROymJ8f",
	"f9pcXgxosvHz+e8wHvvGouzwuvqDgGfFSTf79nb7xNWk8pD/v+eUznD62VM12tWydUyVcyuz/VFNfMJw",
	"UMdBKRwSnFLIkJbnZUSDw5ruEQ5MOYQpLVeXaOlaLv9RwuKrDgmNO6e/YE171IgDlLmt3rxX7g7iy0OU",
	"ywdq4oHK2xqZR56+azHJFZp/5VwVqkmPhLF6kmo/84c6omXc6h+s9t/odjiu770Q7bCi/n1BvyZC58ZD",
	"4xOCvmvslwAnrDI9uF7rdg/6uy/zHtR3X1Q99X/6bNSWfWwAkEoAzlEhCVu4d9mvZlhC5j/Jfl4f/RVc",
	"u0R288jkofy4ZXuSc550vqi+p3l6A7Ya7yUE3MqYaLZB7mr8gEUpXxDWfut0Tim/kwijQtrH9N5zX0Br",
	"gpG54DOv+ldYyjsusobd7WOcofJ9yw2xeSHhBDja7S9veasV3bL6cDizKgng7LrqXuy/rHZHPYvBs+NI",
	"aj4THwSHu4qULxA5msNXgs+JvYk/1qswEPMOtPp/PtyyYET5IEFcOSZPaDDzWiH4Jh4Ecpv0TfRFugGd",
	"NHjQXLYK6l1zXbtlX+m9iv8R3ZOmD+8ZWPD4uSpPqNVBtFT4lzlMyspufU6O7U8R3Ou1oUJ9ty8zzKwe",
	"x7IBLR2M4PaTnee5Zu1y9HJW7uj6yUN1EtqeFgZOKu92d+PP4KDhb62qMCqrN5gvodhzn4iVuae/lRPz",
	"EKh3zL+xq75SQ+8eNbbbGldR2GrAfNS8M/4zx2NV6nOYUHzj3go+zjpfZRQ/GxYlwcsk8xnjVxPDq4ef",
	"p7l28lB+gHzwbjcEJnsn+WgwHa/Rqk+kO97yGAO5690vaCB3Z3vQQIaepm+1tnumOkkSylNMl1yqyQ/j",
	"H8bR9nb7/wAAAP//W11lIrVGAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
