// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
	TokenAuthScopes  = "TokenAuth.Scopes"
)

// Actor defines model for Actor.
type Actor struct {
	ActorType string                  `json:"actor_type"`
	Id        string                  `json:"id"`
	Metadata  *map[string]interface{} `json:"metadata,omitempty"`
	Name      string                  `json:"name"`
}

// Context defines model for Context.
type Context struct {
	Location  string  `json:"location"`
	UserAgent *string `json:"user_agent,omitempty"`
}

// ErrorSchema defines model for ErrorSchema.
type ErrorSchema struct {
	// Error Error custom error code such as 'email_in_use'
	Error string `json:"error"`

	// Message A description about the error
	Message string `json:"message"`
}

// Event defines model for Event.
type Event struct {
	Actor      Actor                   `json:"actor"`
	Context    Context                 `json:"context"`
	Id         string                  `json:"id"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	OccurredAt string                  `json:"occurred_at"`
	SourceId   string                  `json:"source_id"`
	Targets    []Target                `json:"targets"`
	Version    int                     `json:"version"`
}

// EventStream defines model for EventStream.
type EventStream struct {
	Cursor struct {
		Next *string `json:"next,omitempty"`
	} `json:"cursor"`
	Data []Event `json:"data"`
}

// EventType defines model for EventType.
type EventType struct {
	Action                       string    `json:"action"`
	CreatedAt                    time.Time `json:"created_at"`
	Id                           string    `json:"id"`
	Schema                       *string   `json:"schema,omitempty"`
	ShouldValidateMetadataSchema bool      `json:"should_validate_metadata_schema"`
	TargetTypes                  []string  `json:"target_types"`
	UpdatedAt                    time.Time `json:"updated_at"`
	Version                      int       `json:"version"`
}

// EventTypeList defines model for EventTypeList.
type EventTypeList struct {
	Data       []EventType `json:"data"`
	Pagination Pagination  `json:"pagination"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Total       int `json:"total"`
	PerPage     int `json:"per_page"`
	CurrentPage int `json:"current_page"`
	TotalPages  int `json:"total_pages"`
}

// Source defines model for Source.
type Source struct {
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SourceList defines model for SourceList.
type SourceList struct {
	Data       string     `json:"data"`
	Pagination Pagination `json:"pagination"`
}

// Target defines model for Target.
type Target struct {
	Id         string                  `json:"id"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Name       string                  `json:"name"`
	TargetType string                  `json:"target_type"`
}

// EventId defines model for event_id.
type EventId = string

// EventTypeAction defines model for event_type_action.
type EventTypeAction = string

// PaginationCursor defines model for pagination_cursor.
type PaginationCursor = string

// PaginationLimit defines model for pagination_limit.
type PaginationLimit = int

// PaginationPage defines model for pagination_page.
type PaginationPage = int

// SourceId defines model for source_id.
type SourceId = string

// SourceIdQuery defines model for source_id_query.
type SourceIdQuery = string

// Token defines model for token.
type Token = string

// TokenId defines model for token_id.
type TokenId = string

// BadRequestError defines model for BadRequestError.
type BadRequestError = ErrorSchema

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorSchema

// NotFoundError defines model for NotFoundError.
type NotFoundError = ErrorSchema

// CreateEventJSONBody defines parameters for CreateEvent.
type CreateEventJSONBody struct {
	Actor struct {
		Id       string                  `json:"id"`
		Metadata *map[string]interface{} `json:"metadata,omitempty"`
		Name     *string                 `json:"name,omitempty"`
		Type     string                  `json:"type"`
	} `json:"actor"`
	Context struct {
		Location  string  `json:"location"`
		UserAgent *string `json:"user_agent,omitempty"`
	} `json:"context"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	OccurredAt time.Time               `json:"occurred_at"`
	SourceId   string                  `json:"source_id"`
	Targets    []struct {
		Id       string                  `json:"id"`
		Metadata *map[string]interface{} `json:"metadata,omitempty"`
		Name     *string                 `json:"name,omitempty"`
		Type     string                  `json:"type"`
	} `json:"targets"`
	Version int `json:"version"`
}

// CreateEventParams defines parameters for CreateEvent.
type CreateEventParams struct {
	XToken Token `json:"x-token"`
}

// CreateEventTypeJSONBody defines parameters for CreateEventType.
type CreateEventTypeJSONBody struct {
	Action                       string   `json:"action"`
	Schema                       *string  `json:"schema,omitempty"`
	ShouldValidateMetadataSchema bool     `json:"should_validate_metadata_schema"`
	TargetTypes                  []string `json:"target_types"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	SourceId SourceIdQuery `form:"source_id" json:"source_id"`

	// Cursor Opaque cursor returned by the previous page. Omit to start from the most recent event.
	Cursor *PaginationCursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit The number of items per page
	Limit *PaginationLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSourcesParams defines parameters for GetSources.
type GetSourcesParams struct {
	// Limit The number of items per page
	Limit *PaginationLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Page The page number
	Page *PaginationPage `form:"page,omitempty" json:"page,omitempty"`
}

// CreateSourceJSONBody defines parameters for CreateSource.
type CreateSourceJSONBody struct {
	Name string `json:"name"`
}

// CreateSourceTokenJSONBody defines parameters for CreateSourceToken.
type CreateSourceTokenJSONBody struct {
	Name string `json:"name"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody CreateEventJSONBody

// CreateEventTypeJSONRequestBody defines body for CreateEventType for application/json ContentType.
type CreateEventTypeJSONRequestBody CreateEventTypeJSONBody

// CreateSourceJSONRequestBody defines body for CreateSource for application/json ContentType.
type CreateSourceJSONRequestBody CreateSourceJSONBody

// CreateSourceTokenJSONRequestBody defines body for CreateSourceToken for application/json ContentType.
type CreateSourceTokenJSONRequestBody CreateSourceTokenJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create an event
	// (POST /v1/events)
	CreateEvent(ctx echo.Context, params CreateEventParams) error
	// List event types
	// (GET /x/v1/event-types)
	GetEventTypes(ctx echo.Context) error
	// Create an event type
	// (POST /x/v1/event-types)
	CreateEventType(ctx echo.Context) error
	// Archive an event
	// (POST /x/v1/event-types/{event_id}/archive)
	ArchiveEventType(ctx echo.Context, eventId EventId) error
	// Return the details of an Event Type
	// (GET /x/v1/event-types/{event_type_action})
	GetEventTypeByID(ctx echo.Context, eventTypeAction EventTypeAction) error
	// Get events
	// (GET /x/v1/events)
	GetEvents(ctx echo.Context, params GetEventsParams) error
	// List all sources
	// (GET /x/v1/sources)
	GetSources(ctx echo.Context, params GetSourcesParams) error
	// Create a source
	// (POST /x/v1/sources)
	CreateSource(ctx echo.Context) error
	// List all sources
	// (GET /x/v1/sources/{source_id})
	GetSourceByID(ctx echo.Context, sourceId SourceId) error
	// Create source token
	// (POST /x/v1/sources/{source_id}/token)
	CreateSourceToken(ctx echo.Context, sourceId SourceId) error
	// Delete token
	// (DELETE /x/v1/sources/{source_id}/token/{token_id})
	DeleteToken(ctx echo.Context, sourceId SourceId, tokenId TokenId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateEvent converts echo context to params.
func (w *ServerInterfaceWrapper) CreateEvent(ctx echo.Context) error {
	var err error

	ctx.Set(TokenAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateEventParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "x-token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-token")]; found {
		var XToken Token
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for x-token, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-token", valueList[0], &XToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter x-token: %s", err))
		}

		params.XToken = XToken
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter x-token is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateEvent(ctx, params)
	return err
}

// GetEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypes(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventTypes(ctx)
	return err
}

// CreateEventType converts echo context to params.
func (w *ServerInterfaceWrapper) CreateEventType(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateEventType(ctx)
	return err
}

// ArchiveEventType converts echo context to params.
func (w *ServerInterfaceWrapper) ArchiveEventType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "event_id" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "event_id", ctx.Param("event_id"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter event_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ArchiveEventType(ctx, eventId)
	return err
}

// GetEventTypeByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypeByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "event_type_action" -------------
	var eventTypeAction EventTypeAction

	err = runtime.BindStyledParameterWithOptions("simple", "event_type_action", ctx.Param("event_type_action"), &eventTypeAction, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter event_type_action: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventTypeByID(ctx, eventTypeAction)
	return err
}

// GetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvents(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEventsParams
	// ------------- Required query parameter "source_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "source_id", ctx.QueryParams(), &params.SourceId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvents(ctx, params)
	return err
}

// GetSources converts echo context to params.
func (w *ServerInterfaceWrapper) GetSources(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSourcesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSources(ctx, params)
	return err
}

// CreateSource converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSource(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSource(ctx)
	return err
}

// GetSourceByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetSourceByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSourceByID(ctx, sourceId)
	return err
}

// CreateSourceToken converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSourceToken(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSourceToken(ctx, sourceId)
	return err
}

// DeleteToken converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteToken(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceId

	err = runtime.BindStyledParameterWithOptions("simple", "source_id", ctx.Param("source_id"), &sourceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "token_id" -------------
	var tokenId TokenId

	err = runtime.BindStyledParameterWithOptions("simple", "token_id", ctx.Param("token_id"), &tokenId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter token_id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteToken(ctx, sourceId, tokenId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/v1/events", wrapper.CreateEvent)
	router.GET(baseURL+"/x/v1/event-types", wrapper.GetEventTypes)
	router.POST(baseURL+"/x/v1/event-types", wrapper.CreateEventType)
	router.POST(baseURL+"/x/v1/event-types/:event_id/archive", wrapper.ArchiveEventType)
	router.GET(baseURL+"/x/v1/event-types/:event_type_action", wrapper.GetEventTypeByID)
	router.GET(baseURL+"/x/v1/events", wrapper.GetEvents)
	router.GET(baseURL+"/x/v1/sources", wrapper.GetSources)
	router.POST(baseURL+"/x/v1/sources", wrapper.CreateSource)
	router.GET(baseURL+"/x/v1/sources/:source_id", wrapper.GetSourceByID)
	router.POST(baseURL+"/x/v1/sources/:source_id/token", wrapper.CreateSourceToken)
	router.DELETE(baseURL+"/x/v1/sources/:source_id/token/:token_id", wrapper.DeleteToken)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RaW2/jNhb+KwR3gb4oltOZBQo/bWaSFtltO8HEwD4MAoOWjm12JVLDSxoj8H8veNHN",
	"omzJ4/FM36KQPDyX71zpV5zwvOAMmJJ49ooLIkgOCoT9gmdgakFT8zdleIYLojY4wozkgGf1coQFfNZU",
	"QIpnSmiIsEw2kBNzTm0Ls1cqQdka73aRP2b+vyCJopwdJN/cN+6egqwpI+bgItFCcmG2pSATQQt3Lf5Q",
	"kM8akFtGApQWDFK03CK1AVQIeKZcS1SQNUzQh5wqpDiSigiFVoLndlfOpUICEmAKWZYnOHLifNYgtrU8",
	"nonBTGc0p6rL83wDiOl8CQLxFaIKcokKEJbJnpsdpebFOXmhuc7x7PpfEc4p8x9RyRFlCtYg9lmydwQ5",
	"MiuerR4mPH8NHg5fK7kWCfSjr14fB4vq3MIxWFLfY/dU8or/H2pEb4CkViOe6suVWz+BZr8mquUxVHdm",
	"syw4k2B9/R1JP8JnDVLdCeF8JeFMAbMQJEWR0cSCIP5DOpetaf9TwArP8D/iOpjEblXGltqj22pvbWPn",
	"liiCnklGU0scgb18F+F7pkAwkj2CeAZxUZ5u0BoYCJo4blCpJ8PW71z9zDVLL8rQR3BoRIwrtDLXOyS7",
	"04b4TaIcO4XgBQhFnVGJ+ffCmb4DgQg7RHX+nYMiKVGWa5Km1HBBsocGZQcuprOMLDMovz0hvvwDEmUI",
	"OXyGEF3j9BO2wG1w6s897SL83ij3RXUFy7jTc5B/LUEsyNpbpYfLHmYqwub6plk6LECJgLat7BmUaKl4",
	"7vGT8BSQ1MkGEYl+gJzQbEHZQkv4AUch9UsZjLM3qPGNyJJrZTOQ4+SYZOWukvxTwGB3z15pARgdw7CD",
	"4C5yHuGMdmh/adsL4JAniRYC0gWxXK24yM1f2BC/UjSHkBla+aezqohYg6uZbAo+Ju3c7rcnHSkiBNma",
	"72cQso3kZhbsOEozL5VHvfvgmq3aCm3pn0ojPyoBJO+auq6U2v9n3qLHvMnELm+yQXpxiOuoZU9ySzIq",
	"mauEmPvA1kFrX2RIBBAVxAH04qAHAL2ZNcJyw3WWLnxWg0WJ40XnzJLzDAirAWUjYBtVXejtAUgX6Wih",
	"RoKuqr9rxLX4PS5zS/ctnlvW/JXKQPwZjyiLjICu6lr2GJmHemcPGhu0jAwPLdIdrxKmmSnr5z2dR/jl",
	"igtTKM7eGCZBDNj5oy0MFckOb7sut1mS8vDmt/uiugsaLEVtWdq0jRoebXwKqGCs6+0pJeSGe2KGy409",
	"lY32lkPqsc5hrz2A70BCcko6A9i9tncBF/+KUPfJrMP6N6onW8FoYL3ZPFEVnCZ2Q6IFVVtb9fnOCIgA",
	"caPVxnwt7dfPJW7+87952dTagG5XawxtlCoMg3PTopUkjnSGZcwq6H9h61IqvLhm6JYnslsXmkvkLI7X",
	"VG30cpLwPF5RkVPGkw1ha8JoTHRKFaTxx7ub29/uJrlRgRbZqMM2GbIVL7seklgI2HoWz7A/NSmP/Xtt",
	"FgxB3O2wHu6RgBUIYAmgFRfI34FuHu5xhDOagGm4TMHh1PPb/fwEluNf79/f/f5oBTYwAZHLDyvTUtIE",
	"xgkfYUVVZg1T/afKong6mU6ubalZACMFxTP8ZjKdvLG+ozbWaPHzdWwHRG7SxmVguDOZTLAlIqy33ad4",
	"ht/bwOIKpag1ofsU9ut6S+wwtXtyHgBSvePpdlTb2tMJnNXxRzj6CA83W0LBNzlDUzm0iQxcf7JSDnQx",
	"cMYu5m9s2dNbqy/tqtr0jOz787Ufp28DwwLj1MhXDkjqJAEpVzrLti5mrojOehvpinwcmpU1k5mNFI0U",
	"9OnJRASp85yIbRVhEGFugG0lXpv4gh/0MqOJjco2PcYvVRS7qloVXwu0RTPFjSOHyh6hHdZ+AVWV6hJ3",
	"tHV9vuFaq7kIzvsywyxftfjdRfjtdHpc+fuD07Mbrll/7FsuoOXSdDdpTpm3XNSTbkrDIwZ/NsgcSkFz",
	"t362dNIXb7+X/novUFSd8Mj+d1iI+AqgDwHePiHBn9m2Cj0N2/8tcL8XsUrUhrAfilrxa/l2uYuJSDb0",
	"Gfprshu3oRke297hNzTdY1yVVj2kukJtWNbYEImWAAx5Abr54/s3Y0C1Y03YeB/e9Sajj/Zl1w7LU1CE",
	"ZtJEe8KQU+U8FPOa+end9v72RKs2368D5p1ezuPP4+NvHSIPn2u/kp0FUhVmhtnyOIz6S5dQE1aiQY6G",
	"wf578y46eqT7y4Vxh9x7/9dHm39ECODN2ULadaQlZWv/I4urJZGQoprZyWUjzi/g6yV5DCTObqNR8uiP",
	"jYVJ13yjTG6nsV/V4o2ZZbCG9sxAWlXTpQYvXxGTLKtuH1cR9w9g/Kj1XKXvsLfxcjA5tL08o6VDVnYr",
	"F2pYh9R/3soDfTl+rYLx7jS/PqkQqIcLF3DQ8O9HqpQpqweDb5XIz+zIh2wcVz/GOs3Z534i/2Xm/n6j",
	"xbcbRg3wbf+Tp+pV5CTbx6/lj+N2TuAMFAwDwq3d+8UQiIbN6Id3f5Yj5CT5lmZy+jlsH0vP0Hdaq59v",
	"ZnGc8YRkGy7V7KfpT1O8e9r9FQAA///402tNjSwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
