@startuml
actor client as CA
participant webhooks_svc as WS
queue message_queue as MQ
database DB
actor webhook_url_svc as WUS

CA -> CA: Performs an action e.g.: Create user
CA -> WS: Create message e.g.: "user.created"
WS -> DB: Stores message
WS -> MQ: Sends command SendWebhook
WS <-- MQ: Sends command to command handler

loop Until max retries
    WS -> WUS: Calls webhook url with message payload
end

WS -> DB: Stores the result of the webhook call

@enduml