openapi: 3.0.3

info:
  title: audited
  description: API reference for audited API
  termsOfService: https://github.com/firminochangani/audited
  contact:
    email: firmino.changani@gmail.com
  license:
    name: MIT
    url: https://github.com/firminochangani/audited/LICENSE.md
  version: 0.0.1

externalDocs:
  description: https://github.com/firminochangani/audited/README.md
  url: https://github.com/firminochangani/audited

servers:
  - url: http://localhost:8080

paths:
  # Events
  /events:
    post:
      summary: Create an event
      description: ...
      tags:
        - Events
      operationId: createEvent
      security:
        # - ApiKeyAuth: [ ]
      parameters:
        # - $ref: '#/components/parameters/message_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [version, actor, targets, context, occurred_at]
              properties:
                version:
                  type: integer
                actor:
                  type: object
                  required: [id, type]
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    name:
                      type: string
                    metadata:
                      type: object
                      additionalProperties: true
                targets:
                  type: array
                  items:
                    type: object
                    required: [id, type]
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      name:
                        type: string
                      metadata:
                        type: object
                        additionalProperties: true
                context:
                  type: object
                  required: [location]
                  properties:
                    location:
                      type: string
                    user_agent:
                      type: string
                metadata:
                  type: object
                  additionalProperties: true
                occurred_at:
                  type: string
                  format: date-time
      responses:
        "204":
          description: Event created successfully
        default:
          $ref: "#/components/responses/InternalServerError"

  # Event types
  /event-types:
    post:
      summary: Create an event type
      description: Create a new event type
      tags:
        - EventTypes
      operationId: CreateEventType
      security:
        # - ApiKeyAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [ action, target_types, should_validate_metadata_schema ]
              properties:
                action:
                  type: string
                target_types:
                  type: array
                  items:
                    type: string
                should_validate_metadata_schema:
                    type: boolean
                schema:
                  type: string
      responses:
        "201":
          description: The newly created event type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventType"
        "400":
          $ref: '#/components/responses/BadRequestError'
        default:
          $ref: "#/components/responses/InternalServerError"

  /event-types/{event_type_action}:
    get:
      summary: Return the details of an Event Type
      description: Return the details of an Event Type
      tags:
        - EventTypes
      operationId: GetEventTypeByID
      parameters:
        - $ref: '#/components/parameters/event_type_action'
      # security:
      # - ApiKeyAuth: [ ]
      responses:
        "200":
          description: The event type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventType"
        "400":
          $ref: '#/components/responses/BadRequestError'
        "404":
          $ref: '#/components/responses/NotFoundError'
        default:
          $ref: "#/components/responses/InternalServerError"
components:
  parameters:
    event_type_action:
      name: event_type_action
      in: path
      required: true
      schema:
        type: string
    idempotency_key:
      name: idempotency_key
      in: header
      required: false
      schema:
        type: string
    paginationLimit:
      name: limit
      description: The number of items per page
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 15
    paginationPage:
      name: page
      description: The page number
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
  schemas:
    # Event type
    EventType:
      required: [id, action, version, target_types, should_validate_metadata_schema, created_at, updated_at]
      properties:
        id:
          type: string
        version:
          type: integer
        action:
          type: string
        target_types:
          type: array
          items:
            type: string
        schema:
          type: string
        should_validate_metadata_schema:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    EventTypeList:
      required: [ data, pagination ]
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        data:
          type: array
          items:
            $ref: '#/components/schemas/EventType'

    # Pagination
    Pagination:
      required: [ total, per_page, current_page, total_pages ]
      properties:
        total:
          type: integer
          x-order: 1
        per_page:
          type: integer
          x-order: 2
        current_page:
          type: integer
          x-order: 3
        total_pages:
          type: integer
          x-order: 4

    # Error
    ErrorSchema:
      type: object
      required: [error, message]
      properties:
        message:
          type: string
          description: A description about the error
        error:
          type: string
          description: Error custom error code such as 'email_in_use'
  responses:
    UnauthorizedError:
      description: "Usually causes by an authentication token missing"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"
    NotFoundError:
      description: "Resource not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"
    BadRequestError:
      description: "Data validation error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"
    InternalServerError:
      description: "A generic error response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorSchema"
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
