name: coverage
on:
  workflow_call:

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.26.1"

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
